apiVersion: v1
kind: Service
metadata:
  namespace: indexify
  name: indexify-service
spec:
  type: NodePort
  ports:
    - port: 8900
      protocol: TCP
  selector:
    app: indexify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: indexify
  name: indexify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexify
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: indexify
    spec:
      containers:
        - name: indexify
          command: ["./indexify"]
          args:
            - server
            - --config-path
            - ./config/indexify.yaml
          image: tensorlake/indexify
          volumeMounts:
            - mountPath: /indexify/config
              name: config
              readOnly: true
          env:
            - name: AWS_SECRET_ACCESS_KEY
              value: iUGW39NaEl5HCdD78DZ00TcqCEPeYtxfZfu7k4LV
            - name: AWS_ACCESS_KEY_ID
              value: AKIA3FLD5UFGSLYRASMP
      nodeSelector:
        node_role: indexify
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: indexify-configmap
            items:
              - key: "sample_config.yaml"
                path: "indexify.yaml"
